const interests = [
    "’90s kid",
    "Harry Potter",
    "SoundCloud",
    "Spa",
    "Self-care",
    "Heavy metal",
    "House parties",
    "Gin & tonic",
    "Gymnastics",
    "Hot yoga",
    "Meditation",
    "Sushi",
    "Spotify",
    "Hockey",
    "Basketball",
    "Slam poetry",
    "Home workouts",
    "Theatre",
    "Café hopping",
    "Aquarium",
    "Trainers",
    "Instagram",
    "Hot springs",
    "Walking",
    "Running",
    "Travel",
    "Language exchange",
    "Films",
    "Guitarists",
    "Social development",
    "Gym",
    "Social media",
    "Hip hop",
    "Skincare",
    "J-Pop",
    "Shisha",
    "Cricket",
    "Korean dramas",
    "Freelance",
    "K-Pop",
    "Skateboarding",
    "Gospel",
    "Group X",
    "Potterhead",
    "Trying new things",
    "Photography",
    "Bollywood",
    "Reading",
    "Singing",
    "Sports",
    "Poetry",
    "Stand-up comedy",
    "Coffee",
    "Karaoke",
    "Fortnite",
    "Free diving",
    "Self-development",
    "Mental health awareness",
    "Foodie tour",
    "Voter rights",
    "Jiu-jitsu",
    "Climate change",
    "Exhibition",
    "Walking my dog",
    "LGBTQIA+ rights",
    "Feminism",
    "VR room",
    "Escape café",
    "Shopping",
    "Brunch",
    "Investment",
    "Jet skiing",
    "Reggaeton",
    "Vintage clothing",
    "Black Lives Matter",
    "Jogging",
    "Road trips",
    "Vintage fashion",
    "Voguing",
    "Sofa surfing",
    "Happy hour",
    "Inclusivity",
    "Country music",
    "Football",
    "Rollerblading",
    "Investing",
    "Tennis",
    "Ice cream",
    "Ice skating",
    "Human rights",
    "Exhibitions",
    "Pig roast",
    "Skiing",
    "Canoeing",
    "West End musicals",
    "Snowboarding",
    "Pilates",
    "Pentathlon",
    "Broadway",
    "PlayStation",
    "Cheerleading",
    "Choir",
    "Pole dancing",
    "Five-a-side football",
    "Car racing",
    "Pinterest",
    "Festivals",
    "Pub quiz",
    "Catan",
    "Cosplay",
    "Motor sports",
    "Coffee stands",
    "E-sports",
    "Content creation",
    "Bicycle racing",
    "Binge-watching TV series",
    "Songwriter",
    "Bodycombat",
    "Tattoos",
    "Painting",
    "Bodyjam",
    "Paddle boarding",
    "Padel",
    "Blackpink",
    "Surfing",
    "Bowling",
    "Grime",
    "’90s Britpop",
    "Bodypump",
    "Beach bars",
    "Bodystep",
    "Paragliding",
    "Upcycling",
    "V-Pop",
    "Equality",
    "Astrology",
    "Motorcycles",
    "Equestrian",
    "Bun cha",
    "Entrepreneurship",
    "Sake",
    "BTS",
    "Cooking",
    "Environmental protection",
    "Fencing",
    "Football",
    "Saxophonist",
    "Sci-fi",
    "Dancing",
    "Film festivals",
    "Freeletics",
    "Gardening",
    "Amateur cook",
    "Exchange programmes",
    "Sauna",
    "Art",
    "Politics",
    "Flamenco",
    "Museum",
    "Activism",
    "Running Man",
    "DAOs",
    "Real estate",
    "Podcasts",
    "Disability rights",
    "Rap Viet",
    "Rave",
    "Pimms",
    "BBQ",
    "Drive-in cinema",
    "Rock climbing",
    "Craft beer",
    "Iced tea",
    "Drummer",
    "Tea",
    "Board games",
    "Roblox",
    "Pubs",
    "Rock",
    "Tango",
    "Drawing",
    "Trivia",
    "Pho",
    "Volunteering",
    "Environmentalism",
    "Rollerskating",
    "Wine",
    "Dungeons & Dragons",
    "Hot pot",
    "Vlogging",
    "Electronic music",
    "Ramen",
    "Weightlifting",
    "Live music",
    "Writing",
    "Xbox",
    "World peace",
    "Wrestling",
    "Literature",
    "Manga",
    "Pride",
    "Marathon",
    "Make-up",
    "Youth empowerment",
    "YouTube",
    "Martial arts",
    "Marvel",
    "Vegan cooking",
    "Vermouth",
    "Korean food",
    "Twitter",
    "Volleyball",
    "Walking tours",
    "Vinyasa",
    "Virtual reality",
    "League of Legends",
    "NFTs",
    "Pub crawls",
    "Nintendo",
    "Baseball",
    "Parties",
    "Ballet",
    "Bands",
    "Online games",
    "Battle Ground",
    "Beach tennis",
    "Nightlife",
    "Online shopping",
    "Sailing",
    "Olympic gymnastics",
    "Bassist",
    "Online broker",
    "Military",
    "Memes",
    "Among Us",
    "Motorbike racing",
    "Motorcycling",
    "Metaverse",
    "Mindfulness",
    "Acapella",
    "Playing a musical instrument",
    "Art galleries",
    "Writing musicals",
    "Hiking",
    "Artistic gymnastics",
    "Mountains",
    "Archery",
    "Atari",
    "Backpacking",
    "Fishing",
    "Clubbing",
    "Street food",
    "Crossfit",
    "Concerts",
    "Climbing",
    "Baking",
    "Camping",
    "Blogging",
    "Collecting",
    "Cars",
    "Start-ups",
    "Boba tea",
    "High-school baseketball league (TW)",
    "Badminton",
    "Active lifestyle",
    "Fashion",
    "Anime",
    "NBA",
    "MLB",
    "Funk music",
    "Caipirinha",
    "Indoor activities",
    "Tempeh",
    "DIY",
    "Town festivities",
    "Cycling",
    "Outdoors",
    "TikTok",
    "Picnicking",
    "Twitch",
    "Comedy",
    "Trap music",
    "Music",
    "Triathlon",
    "Netflix",
    "Disney",
    "Rugby",
    "Açaí",
    "Samba",
    "Tarot",
    "Stock exchange",
    "Stocks",
    "Swimming",
    "Table tennis",
    "Killing time",
    "Working out",
    "Yoga",
    "Horror films",
    "Boxing",
    "Chilling at a bar"
]
export default interests;